- name: Create Folder /srv/nodeserver if not exist
  ansible.builtin.file:
    path: /srv/nodeserver
    mode: 0777
    state: directory
  become: true

- name: Copy configuration folder
  ansible.builtin.copy:
    dest: /srv
    src: roles/pi-setup/files/nodeserver
    mode: 0644
  become: true

- name: Create nodeserver container
  docker_container:
    image: node:alpine
    name: nodeserver
    restart_policy: always
    command: /bin/sh -c "cd /srv/app && npm install && node index.js"
    published_ports: "8080:8082"
    volumes:
     - type: bind
        source: ./
        target: /srv/app
  become: true
