- name: Create Folder /srv/grafana/data if not exist
  ansible.builtin.file:
    path: /srv/grafana/data
    mode: 0777
    state: directory
  become: true

- name: Copy configuration file
  ansible.builtin.copy:
    dest: /srv
    src: roles/monitoring/files/grafana
    mode: 0644
  become: true

- name: Stop and remove container Grafana
  docker_container:
    name: "grafana"
    state: absent

- name: Create Grafana container
  ansible.builtin.docker_container:
    name: grafana
    restart_policy: always
    image: grafana/grafana
    networks:
      - name: monitoring
    volumes:
      - /srv/grafana/data:/var/lib/grafana
      - /srv/grafana/provisioning:/etc/grafana/provisioning
      - /srv/grafana/dashboards:/var/lib/grafana/dashboards
    env:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
    ports:
      - "3000:3000"
  become: true
