- name: Create Folder /srv/prometheus/data if not exist
  ansible.builtin.file:
    path: /srv/prometheus/data
    mode: 0777
    state: directory
  become: true

- name: Create prometheus configuration file
  ansible.builtin.copy:
    dest: /srv/prometheus/prometheus.yml
    src: prometheus_main.yml
    mode: 0644
  become: true

- name: Create prometheus alert configuration file
  copy:
    dest: /srv/prometheus/prometheus_alerts_rules.yml
    src: prometheus_alerts_rules.yml
    mode: 0777

- name: Stop and remove container Prometheus
  docker_container:
    name: "prometheus"
    state: absent

- name: Create Prometheus container
  ansible.builtin.docker_container:
    name: prometheus
    restart_policy: always
    image: prom/prometheus
    networks:
      - name: monitoring
    volumes:
      - /srv/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - /srv/prometheus/prometheus_alerts_rules.yml:/etc/prometheus/rules/prometheus_alerts_rules.yml
      - /srv/prometheus/data:/prometheus
    command: >
      --config.file=/etc/prometheus/prometheus.yml
      --storage.tsdb.path=/prometheus
      --web.console.libraries=/etc/prometheus/console_libraries
      --web.console.templates=/etc/prometheus/consoles
      --web.enable-lifecycle
    ports:
      - "9090:9090"
  become: true
