- name: Create Folder /srv/prometheus if not exist
  ansible.builtin.file:
    path: /srv/prometheus
    mode: 0755
    state: directory
  become: true

- name: Create prometheus configuration file
  ansible.builtin.copy:
    dest: /srv/prometheus/prometheus.yml
    src: prometheus_main.yml
    mode: 0644
  become: true

- name: Create Prometheus container
  ansible.builtin.docker_container:
    name: prometheus
    restart_policy: always
    image: prom/prometheus
    networks:
      - name: monitoring
    volumes:
      - /srv/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_main_data:/prometheus
    command: >
      --config.file=/etc/prometheus/prometheus.yml
      --storage.tsdb.path=/prometheus
      --web.console.libraries=/etc/prometheus/console_libraries
      --web.console.templates=/etc/prometheus/consoles
      --web.enable-lifecycle
    ports:
      - "9090:9090"
  become: true
