version: "3.4"
services:
  os_info_api:
    image: node:alpine
    container_name: OsInfo
    command: /bin/sh -c "cd /srv/app && npm install && node index.js"
    ports:
      - 4000:4000
    working_dir: /srv/app
    volumes:
      - type: bind
        source: ./
        target: /srv/app
    tty: true
