groups:
  - name: example
    rules:
      - alert: cAdvisor is down
        expr: up{job="cadvisor"} == 0
        for: 1m
        labels:
          severity: warning
          sendto: telegram
        annotations:
          summary: "Instance {{ $labels.instance }} down"
          description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute."

  - name: Alert all the time
    rules:
      - alert: Just another alert
        expr: vector(1)
        for: 1m
        labels:
          severity: page
          sendto: telegram
        annotations:
          summary: "Test please ignore"
          description: "This is an alert that fires all the time."
