rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - "alertmanager:9093"

scrape_configs:
  - job_name: prometheus
    scrape_interval: 30s
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: node-exporter
    scrape_interval: 30s
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: cadvisor
    scrape_interval: 30s
    static_configs:
      - targets: ["cadvisor:8080"]
